# Generated by Django 5.2.3 on 2025-07-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='notes',
            new_name='note',
        ),
    ]
